export const videoCompressionPresets = [
  {
    id: 1,
    label: "1080p HD",
    description: "Full HD quality - best for desktop viewing",
    resolution: "1920x1080",
    crf: 23,
    videoCodec: "libx264" as const,
    preset: "medium" as const,
    fps: 30,
    keyframeInterval: 60,
    audioBitrate: "128k",
    estimatedSize: "30-50MB per minute",
  },
  {
    id: 2,
    label: "720p HD",
    description: "HD quality - balanced size and quality",
    resolution: "1280x720",
    crf: 23,
    videoCodec: "libx264" as const,
    preset: "medium" as const,
    fps: 30,
    keyframeInterval: 60,
    audioBitrate: "96k",
    estimatedSize: "15-25MB per minute",
  },
  {
    id: 3,
    label: "480p SD",
    description: "Standard definition - smaller file size",
    resolution: "854x480",
    crf: 24,
    videoCodec: "libx264" as const,
    preset: "fast" as const,
    fps: 30,
    keyframeInterval: 90,
    audioBitrate: "64k",
    estimatedSize: "8-12MB per minute",
  },
];
